{% set name = "napari-aideveloper" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-aideveloper-{{ version }}.tar.gz
  sha256: 107c89de1e8c85ddc487058a70a1f04123aa44653eaa0493c410403c18b1162f
  patches:
    - warnings.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - dclab >=0.39.9
    - h5py >=3.6.0
    - keras >=2.8.0
    - keras-applications >=1.0.8
    - keras-metrics >=1.1.0
    - magicgui
    - napari >=0.4.14
    - napari-plugin-engine >=0.2.0
    - numpy
    - onnx >=1.11.0
    - opencv >=4.5.5.62
    - openpyxl >=3.0.9
    - pandas >=1.4.1
    - pillow >=9.1.1
    - psutil >=5.9.0
    - pyqtgraph >=0.12.3
    - pytest >=7.1.2
    - python >=3.8
    - qtpy
    - scikit-learn >=1.1.1
    - scipy >=1.8.0
    - setuptools >=58.0.4
    - six >=1.16.0
    - tensorboard >=2.8.0
    - tensorflow >=2.8.0
    - tf2onnx >=1.9.3
    - xlrd >=2.0.1

test:
  imports:
    - napari_aideveloper
  commands:
    - pip list
    # - pip check  # Fails due to opencv-contrib-python-headless
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-aideveloper
  summary: |
    napari_aideveloper is a napari-plugin deived from AIDeveloper that allows you to train,
    evaluate and apply deep neural nets for image classification within a graphical
    user-interface (GUI).
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/zcqwh/napari-aideveloper

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
